src/main/java/com/iemr/common/config/SwaggerConfig.java

Adding swagger configuration changes

Adding swagger configuration changes

---

src/main/java/com/iemr/common/controller/users/IEMRAdminController.java

Authentication api for bhavya for plain text

bhavya authentication api for plain text

---

src/main/java/com/iemr/common/model/esanjeevani/ESanjeevaniPatientAddress.java
src/main/java/com/iemr/common/model/esanjeevani/ESanjeevaniPatientContactDetail.java
src/main/java/com/iemr/common/model/esanjeevani/ESanjeevaniPatientRegistration.java

sonarqube reported vilnerability

---

src/main/java/com/iemr/common/config/BlockingHttpMethodInterceptor.java
src/main/java/com/iemr/common/config/InterceptorConfig.java

 http changes

---

src/main/environment/common_ci.properties
src/main/environment/common_dev.properties
src/main/environment/common_example.properties
src/main/environment/common_test.properties
src/main/environment/common_uat.properties
src/main/java/com/iemr/common/service/email/EmailServiceImpl.java
src/main/resources/application.properties
src/main/resources/myapp.properties

- Tested by packaging the build

Moved all env specific properties to respective env files

---

src/main/environment/common_ci.properties
src/main/environment/common_dev.properties
src/main/environment/common_example.properties
src/main/environment/common_test.properties
src/main/environment/common_uat.properties
src/main/java/com/iemr/common/controller/eausadha/EAusadhaController.java
src/main/java/com/iemr/common/data/eausadha/ItemMaster.java
src/main/java/com/iemr/common/data/eausadha/ItemStockEntry.java
src/main/java/com/iemr/common/data/facility/Facility.java
src/main/java/com/iemr/common/model/eAusadha/EAusadhaDTO.java
src/main/java/com/iemr/common/repository/brd/BRDIntegrationRepository.java
src/main/java/com/iemr/common/repository/eausadha/ItemMasterRepo.java
src/main/java/com/iemr/common/repository/eausadha/ItemStockEntryRepo.java
src/main/java/com/iemr/common/repository/email/StockAlertDataRepo.java
src/main/java/com/iemr/common/repository/facility/FacilityRepo.java
src/main/java/com/iemr/common/repository/nhm_dashboard/AbandonCallSummaryRepo.java
src/main/java/com/iemr/common/repository/nhm_dashboard/AgentSummaryReportRepo.java
src/main/java/com/iemr/common/repository/nhm_dashboard/DetailedCallReportRepo.java
src/main/java/com/iemr/common/repository/nhm_dashboard/LineCallSummaryRepo.java
src/main/java/com/iemr/common/repository/nhm_dashboard/NHMAgentRealTimeDataRepo.java
src/main/java/com/iemr/common/repository/report/CallReportRepo.java
src/main/java/com/iemr/common/repository/uptsu/FacilityMasterRepo.java
src/main/java/com/iemr/common/repository/uptsu/T_104AppointmentDetailsRepo.java
src/main/java/com/iemr/common/service/beneficiary/EAusadhaService.java
src/main/java/com/iemr/common/service/beneficiary/EAusadhaServiceImpl.java
src/main/resources/application.properties

Swagger Api documentation disclosure and Eausadha integration

---

pom.xml
src/main/java/com/iemr/common/service/callhandling/BeneficiaryCallServiceImpl.java
src/main/java/com/iemr/common/service/reports/CallReportsServiceImpl.java
src/main/java/common/iemr/common/secondary/data/report/SecondaryCallReport.java

vulnerabilities fixed

---

src/main/java/com/iemr/common/controller/customization/CustomizationController.java
src/main/java/com/iemr/common/data/customization/ProjectCustomization.java
src/main/java/com/iemr/common/data/customization/SectionMasterCustomization.java
src/main/java/com/iemr/common/data/customization/ServicelineCustomization.java
src/main/java/com/iemr/common/repo/customization/ProjectCustomizationRepo.java
src/main/java/com/iemr/common/repo/customization/SectionMasterCustomizationRepo.java
src/main/java/com/iemr/common/repo/customization/ServicelineCustomizationRepo.java
src/main/java/com/iemr/common/service/customization/CustomizationService.java
src/main/java/com/iemr/common/service/customization/CustomizationServiceImpl.java

Customization changes

---

src/main/java/com/iemr/common/mapper/BenCompleteDetailMapperDecorator.java

Mapper class modified

---

src/main/java/com/iemr/common/mapper/BenCompleteDetailMapperDecorator.java

SearchUserById api logic corrected

---

pom.xml
src/main/java/com/iemr/common/service/beneficiary/IEMRSearchUserServiceImpl.java

Feature/amm 805/m1 search not happening by abha number

---

src/main/java/com/iemr/common/service/beneficiary/IEMRSearchUserServiceImpl.java

Abha search change

---

src/main/java/com/iemr/common/dto/identity/CommonIdentityDTO.java

faceEmbedding changes

---

src/main/java/com/iemr/common/controller/kmfilemanager/KMFileManagerController.java

JIRA ID: 964
Please provide a summary of the change and the motivation behind it. Include relevant context and details.
---
---
Please describe how the changes were tested, and include any relevant screenshots, logs, or other information that provides additional context.

changes related to autowiring in KMFileManager

---

src/main/java/com/iemr/common/service/sms/SMSServiceImpl.java

JIRA ID: AMM-1085
Assam prod sms not sending because of flag
---
---
Please describe how the changes were tested, and include any relevant screenshots, logs, or other information that provides additional context.

Assam prod SMS issue

---

src/main/environment/common_ci.properties

JIRA ID: NA
Change SMS scheduler to true.
---

fix: change sms shceduler to true

---

src/main/java/com/iemr/common/service/beneficiary/IdentityBeneficiaryServiceImpl.java

fix IDENTITY_BASE_URL  exception
---
---

IDENTITY_BASE_URL fix

---

src/main/environment/common_docker.properties

fix IDENTITY_API_BASE_URL variable in docker file

---

src/main/java/com/iemr/common/utils/JwtUserIdValidationFilter.java

Add ServerAuthorization key in allow headers

---

pom.xml
src/main/java/com/iemr/common/CommonApplication.java
src/main/java/com/iemr/common/config/RedisConfig.java
src/main/java/com/iemr/common/data/userbeneficiarydata/Language.java
src/main/java/com/iemr/common/data/users/User.java

JIRA ID: [AMM-1756](https://support.piramalfoundation.org/jira/browse/AMM-1756)
Please provide a summary of the change and the motivation behind it. Include relevant context and details.
---
---
Please describe how the changes were tested, and include any relevant screenshots, logs, or other information that provides additional context.

Release 3.2.1 to main Branch merge

---

src/main/environment/common_ci.properties
src/main/environment/common_docker.properties
src/main/java/com/iemr/common/service/kmfilemanager/KMFileManagerServiceImpl.java
src/main/resources/application.properties

JIRA ID: [AMM-1519](https://support.piramalfoundation.org/jira/browse/AMM-1519)
Please provide a summary of the change and the motivation behind it. Include relevant context and details.
---
---
**Summary**
This PR introduces changes as part of VAPT (Vulnerability Assessment & Penetration Testing) remediation to strengthen file upload handling and ensure secure processing.
**Changes Implemented**
1.Enforced allowed file extensions via environment property allowed.file.extensions.
2. Extracted and validated file extensions both from filename and payload.
3.  Enforced strict extension matching between filename and payload.
4. Rejected uploads if file extension is missing, mismatched, or not in the allowed list.
5. Normalized file names by removing risky/special characters (', $, \, /, ;, …

VAPT: File Upload Validation and Security Hardening

---

src/main/java/com/iemr/common/filter/PlatformFeedbackRateLimitFilter.java

fix: dev-linux issue fix
